### PR TITLE
add new error type: NoEnoughData

### PR DESCRIPTION
**Pull request by afpro**
add a new error type, i will test this in my project this week.

### CODE REVIEW

**Comment by afpro** [comment]
this change works pretty good so far in my project, but this pull request introduced a new error type, which will lead to a breaking change. it's up to you to decide when to merge it.

**Comment by balliegojr** [comment]
Hello @afpro

Thanks for the contribution.

Can you also add a change in the `CHANGELOG.md` file? 

Something like this
```
## unreleased
- Add new error type
```

Thanks

**Comment by afpro** [comment]
i'll add chang log after work.

**Comment by afpro** [comment]
English is not my first language, that's my best effort. 
(°ー°〃)

**Comment by balliegojr** [comment]
thanks @afpro

**Comment by afpro** [comment]
btw, i highly suggest add '#[non_exhaustive]' to error types.

**Pull request merged**
